name: Daily Run

on:
  schedule:
    - cron: '*/5 * * * *'

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-pytest:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the version of Python you need
        ref: main
    - name: Install dependencies
      run: pip install -r requirements.txt  # If you have a requirements.txt file
    - name: Run pytest
      run: pytest legit_project.py --username ${{ secrets.USER_NAME }} --password ${{ secrets.USER_PASS }}
